In [1]:
import numpy as np

In [2]:
arr=np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
'Broadcasting:- Doesnt happen in Python List'

'Broadcasting:- Doesnt happen in Python List'

In [8]:
arr[0:5]=100

In [9]:
arr
#Cant do this in python list pog

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
arr =np.arange(0,11)

In [11]:
'Slicing'
slice_of_arr =arr[0:5]

In [12]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [13]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99])

In [14]:
arr_copy =arr.copy()
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [15]:
'Indexing in 2d arrays'

'Indexing in 2d arrays'

In [16]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [17]:
arr_2d.shape

(3, 3)

In [21]:
arr_2d[0]

array([ 5, 10, 15])

In [20]:
arr_2d[1,1]

25

In [22]:
'Slicing'
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [23]:
'Conditional Selection'
arr>5

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True])

In [24]:
bool_arr=arr>5

In [25]:
arr[bool_arr]

array([99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [27]:
arr[arr>5]

array([99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
'''
I can perform a comparison within my array
and then pass that as my conditional selection filter

'''