In [2]:
import numpy as np
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [6]:
arr/arr #nan=not a number

C:\Users\Ashut\AppData\Local\Temp\ipykernel_7468\3641532207.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr #nan=not a number


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [7]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [8]:
np.log(arr)

C:\Users\Ashut\AppData\Local\Temp\ipykernel_7468\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [9]:
arr.sum()

45

In [10]:
arr.var()

8.25

In [11]:
arr.std()

2.8722813232690143

In [16]:
arr2d=np.arange(0,25).reshape(4,4)
arr2d

ValueError: cannot reshape array of size 25 into shape (4,4)

In [13]:
arr2d.sum()

300

In [14]:
arr2d.sum(axis=0) #It means perform the operation across rows

array([50, 55, 60, 65, 70])

In [15]:
arr2d.sum(axis=1) #It means perform the operation across columns

array([ 10,  35,  60,  85, 110])