In [4]:
import numpy as np

In [6]:
mylist =[1,2,3]

In [7]:
type(mylist)

list

In [8]:
np.array(mylist)

array([1, 2, 3])

In [9]:
mylist

[1, 2, 3]

In [1]:
my_matrix =[[1,2,3],[4,5,6],[7,8,9]]

In [2]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10,2) #equivalent to range fucntion 

array([0, 2, 4, 6, 8])

In [8]:
np.zeros(5) #dot indicating that it is a floating  point number

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((5,5)) #double brackets

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.linspace(0,10,3) #Returns 3 evenly spaced numbers between 0 and 10

array([ 0.,  5., 10.])

In [13]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [14]:
np.eye(5) #Gives an identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.random.rand(1)

array([0.15863218])

In [22]:
np.random.rand(5,2)

array([[0.93472193, 0.80191188],
       [0.70643115, 0.33712422],
       [0.51092316, 0.19747517],
       [0.46532713, 0.18438421],
       [0.92801985, 0.95864627]])

In [23]:
np.random.randn(10) #Near zero numbers = Standard Normal

array([-0.01284957,  0.53969681, -1.48361055, -0.00993401, -0.30609097,
        1.96619831,  1.27948391,  0.57951047, -0.14278305, -1.06786347])

In [27]:
np.random.randint(0,101,(5,5))

array([[81, 43, 81, 79, 99],
       [34, 66, 32, 99,  3],
       [49, 53, 38, 60, 11],
       [ 5, 22, 52, 88, 32],
       [99,  4, 74, 54, 10]])

In [29]:
np.random.seed(42) #Set a particular set
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [31]:
arr =np.arange(0,25)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
arr.reshape(5,5) # 5x5 =25

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
ranarr=np.random.randint(0,101,10)

In [35]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [38]:
ranarr.max()

99

In [39]:
ranarr.min()

2

In [40]:
ranarr.argmax()

5

In [41]:
ranarr.argmin()

7

In [42]:
ranarr.dtype

dtype('int32')

In [43]:
arr.shape

(25,)

In [44]:
arr =arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])